#!/usr/bin/env python3
"""Rebuild .gid/docs/issues-index.md from ISS-NNN/issue.md frontmatter."""
import re, sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]   # .gid/issues
PROJECT = ROOT.parents[1]
OUT = PROJECT / ".gid" / "docs" / "issues-index.md"
PROJ_NAME = PROJECT.name

def parse_fm(text):
    if not text.lstrip().startswith("---"): return None
    lines = text.splitlines()
    end = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = i; break
    if end is None: return None
    fm = {}
    for line in lines[1:end]:
        m = re.match(r'^([a-zA-Z_]+):\s*(.*)$', line)
        if not m: continue
        k, v = m.group(1), m.group(2).strip()
        if v.startswith('"') and v.endswith('"'): v = v[1:-1]
        if v.startswith("[") and v.endswith("]"):
            v = [x.strip().strip('"') for x in v[1:-1].split(",") if x.strip()]
        fm[k] = v
    return fm

issues = []
for d in sorted(ROOT.iterdir()):
    if not d.is_dir() or not d.name.startswith("ISS-"): continue
    f = d / "issue.md"
    if not f.exists(): continue
    fm = parse_fm(f.read_text())
    if fm is None: continue
    fm["_path"] = f"`.gid/issues/{d.name}/issue.md`"
    issues.append(fm)

PRIO = {"P0":0,"P1":1,"P2":2,"P3":3}
groups = {}
for i in issues:
    groups.setdefault(i.get("status","open"), []).append(i)
for k in groups:
    groups[k].sort(key=lambda x: (PRIO.get(x.get("priority","P3"),99), x.get("id","")))

now = datetime.now().strftime("%Y-%m-%d %H:%M")
out = [f"# Issues: {PROJ_NAME}", "",
       "> AUTO-GENERATED by project-issues skill v5. DO NOT EDIT BY HAND.",
       "> Source: `.gid/issues/ISS-NNN/issue.md` frontmatter.",
       f"> Last rebuilt: {now}", "",
       f"**Total**: {len(issues)} issues", ""]
for label, key in [("Open","open"),("In Progress","in_progress"),("Blocked","blocked"),
                   ("Closed","closed"),("Won't Fix","wontfix"),("Superseded","superseded")]:
    items = groups.get(key, [])
    if not items: continue
    out.append(f"## {label} ({len(items)})")
    out.append("")
    for i in items:
        out.append(f"### {i.get('id','?')} [{i.get('priority','P?')}] {i.get('title','?')}")
        bits = []
        if "created" in i: bits.append(f"**Created**: {i['created']}")
        if "closed" in i: bits.append(f"**Closed**: {i['closed']}")
        if "component" in i: bits.append(f"**Component**: {i['component']}")
        if bits: out.append("  |  ".join(bits))
        for k in ("depends_on","related","supersedes"):
            if k in i:
                v = i[k] if isinstance(i[k], list) else [i[k]]
                out.append(f"**{k.replace('_',' ').title()}**: " + ", ".join(v))
        if "superseded_by" in i: out.append(f"**Superseded by**: {i['superseded_by']}")
        if "note" in i: out.append(f"_{i['note']}_")
        out.append(f"Path: {i['_path']}")
        out.append("")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(out))
print(f"Wrote {OUT} ({len(issues)} issues)")
